-- MySQL Script generated by MySQL Workbench
-- seg 17 ago 2020 21:43:57 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema financeiro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema financeiro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `financeiro` DEFAULT CHARACTER SET utf8 ;
USE `financeiro` ;

-- -----------------------------------------------------
-- Table `financeiro`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`cliente` (
  `cpf` VARCHAR(11) NOT NULL,
  `email` VARCHAR(45) NULL,
  `aniversario` VARCHAR(15) NULL,
  `nome` VARCHAR(90) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`renda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`renda` (
  `cpf` VARCHAR(11) NOT NULL,
  `profissao` VARCHAR(45) NULL,
  `salario` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_renda_1`
    FOREIGN KEY (`cpf`)
    REFERENCES `financeiro`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`endereco` (
  `cpf` VARCHAR(11) NOT NULL,
  `cidade` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `rua` VARCHAR(45) NULL,
  `bairro` VARCHAR(45) NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_endereco_1`
    FOREIGN KEY (`cpf`)
    REFERENCES `financeiro`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`historico_pagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`historico_pagamento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpfComprador` VARCHAR(11) NULL,
  `valor` DOUBLE NULL,
  `cpfFavorecido` VARCHAR(11) NOT NULL,
  `dataVencimento` DATE NULL,
  `dataPagamento` DATE NULL,
  `formaPagamento` VARCHAR(2) NULL,
  `parcelasQuantidade` INT NULL,
  PRIMARY KEY (`id`, `cpfFavorecido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`cartao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`cartao` (
  `cpf` VARCHAR(11) NOT NULL,
  `numero` VARCHAR(22) NULL,
  `senha` VARCHAR(45) NULL,
  `limite` DOUBLE NULL,
  `valorMomento` DOUBLE NULL,
  `dia-fechamento` VARCHAR(8) NULL,
  PRIMARY KEY (`cpf`),
  CONSTRAINT `fk_cartao_1`
    FOREIGN KEY (`cpf`)
    REFERENCES `financeiro`.`cliente` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`score`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`score` (
  `cpf` VARCHAR(11) NOT NULL,
  `score` VARCHAR(45) NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `financeiro`.`boletoPagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `financeiro`.`boletoPagamento` (
  `idPagamento` INT NOT NULL,
  `numero` VARCHAR(45) NULL,
  PRIMARY KEY (`idPagamento`),
  CONSTRAINT `fk_boletoPagamento_1`
    FOREIGN KEY (`idPagamento`)
    REFERENCES `financeiro`.`historico_pagamento` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
